# -*- coding: utf-8 -*-
"""DogsCats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzfoujRA7tAfp9E9pI1Xmp7h1IOFtSO6
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/MyDrive/"Colab Notebooks"/projects/DogsCats
# !unzip dogs-vs-cats.zip -d dogs-vs-cats
# %cd dogs-vs-cats/

# Commented out IPython magic to ensure Python compatibility.
# %ls

import cv2
import numpy as np
import os
from keras.preprocessing.image import ImageDataGenerator
import tensorflow.keras.backend as K
import keras
from keras.models import Sequential, Model,load_model
from keras.optimizers import SGD
from keras.callbacks import EarlyStopping,ModelCheckpoint
from google.colab.patches import cv2_imshow
from keras.layers import Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D,MaxPool2D
from keras.preprocessing import image
from keras.initializers import glorot_uniform

import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    print("Name:", gpu.name, "  Type:", gpu.device_type)

train_path="/content/gdrive/MyDrive/Colab Notebooks/projects/DogsCats/dogs-vs-cats/train"
test_path="/content/gdrive/MyDrive/Colab Notebooks/projects/DogsCats/dogs-vs-cats/test1"
class_names=os.listdir(train_path)
class_names_test=os.listdir(test_path)

print(class_names)
print(class_names_test)

import glob
for file in glob.glob()